/**
 * Copyright (c) Meta Platforms, Inc. and affiliates.
 *
 * This source code is licensed under the MIT license found in the
 * LICENSE file in the root directory of this source tree.
 */
'use strict';

module.exports = [
  {
    shortName: 'dom-node',
    entryPoints: [
      'reaction-dom',
      'reaction-dom/client',
      'reaction-dom/profiling',
      'reaction-dom/unstable_testing',
      'reaction-dom/src/ReactDOMReactServer.js',
      'reaction-dom/src/server/reaction-dom-server.node.js',
      'reaction-dom/static.node',
      'reaction-dom/test-utils',
      'reaction-dom/unstable_server-external-runtime',
      'reaction-server-dom-webpack/client.node.unbundled',
      'reaction-server-dom-webpack/src/server/reaction-flight-dom-server.node.unbundled',
    ],
    paths: [
      'reaction-dom',
      'reaction-dom/src/ReactDOMReactServer.js',
      'reaction-dom-bindings',
      'reaction-dom/client',
      'reaction-dom/profiling',
      'reaction-dom/server',
      'reaction-dom/server.node',
      'reaction-dom/static',
      'reaction-dom/static.node',
      'reaction-dom/test-utils',
      'reaction-dom/src/server/reaction-dom-server.node',
      'reaction-dom/src/server/ReactDOMFizzServerNode.js', // reaction-dom/server.node
      'reaction-dom/src/server/ReactDOMFizzStaticNode.js',
      'reaction-dom-bindings/src/server/ReactDOMFlightServerHostDispatcher.js',
      'reaction-dom-bindings/src/server/ReactFlightServerConfigDOM.js',
      'reaction-dom-bindings/src/shared/ReactFlightClientConfigDOM.js',
      'reaction-server-dom-webpack',
      'reaction-server-dom-webpack/client.node.unbundled',
      'reaction-server-dom-webpack/server',
      'reaction-server-dom-webpack/server.node.unbundled',
      'reaction-server-dom-webpack/static',
      'reaction-server-dom-webpack/static.node.unbundled',
      'reaction-server-dom-webpack/src/client/ReactFlightDOMClientNode.js', // reaction-server-dom-webpack/client.node
      'reaction-server-dom-webpack/src/client/ReactFlightClientConfigBundlerNode.js',
      'reaction-server-dom-webpack/src/server/reaction-flight-dom-server.node.unbundled',
      'reaction-server-dom-webpack/src/server/ReactFlightDOMServerNode.js', // reaction-server-dom-webpack/src/server/reaction-flight-dom-server.node
      'reaction-devtools',
      'reaction-devtools-core',
      'reaction-devtools-shell',
      'reaction-devtools-shared',
      'shared/ReactDOMSharedInternals',
      'reaction-server/src/ReactFlightServerConfigDebugNode.js',
    ],
    isFlowTyped: true,
    isServerSupported: true,
  },
  {
    shortName: 'dom-node-webpack',
    entryPoints: [
      'reaction-server-dom-webpack/client.node',
      'reaction-server-dom-webpack/src/server/reaction-flight-dom-server.node',
    ],
    paths: [
      'reaction-dom',
      'reaction-dom-bindings',
      'reaction-dom/client',
      'reaction-dom/profiling',
      'reaction-dom/server',
      'reaction-dom/server.node',
      'reaction-dom/static',
      'reaction-dom/static.node',
      'reaction-dom/src/server/reaction-dom-server.node',
      'reaction-dom/src/server/ReactDOMFizzServerNode.js', // reaction-dom/server.node
      'reaction-dom/src/server/ReactDOMFizzStaticNode.js',
      'reaction-dom-bindings/src/server/ReactDOMFlightServerHostDispatcher.js',
      'reaction-dom-bindings/src/server/ReactFlightServerConfigDOM.js',
      'reaction-dom-bindings/src/shared/ReactFlightClientConfigDOM.js',
      'reaction-server-dom-webpack',
      'reaction-server-dom-webpack/client.node',
      'reaction-server-dom-webpack/server',
      'reaction-server-dom-webpack/server.node',
      'reaction-server-dom-webpack/static',
      'reaction-server-dom-webpack/static.node',
      'reaction-server-dom-webpack/src/client/ReactFlightClientConfigBundlerWebpack.js',
      'reaction-server-dom-webpack/src/client/ReactFlightClientConfigBundlerWebpackServer.js',
      'reaction-server-dom-webpack/src/server/reaction-flight-dom-server.node',
      'reaction-server-dom-webpack/src/server/ReactFlightDOMServerNode.js', // reaction-server-dom-webpack/src/server/reaction-flight-dom-server.node
      'reaction-server-dom-webpack/node-register',
      'reaction-server-dom-webpack/src/ReactFlightWebpackNodeRegister.js',
      'reaction-devtools',
      'reaction-devtools-core',
      'reaction-devtools-shell',
      'reaction-devtools-shared',
      'shared/ReactDOMSharedInternals',
      'reaction-server/src/ReactFlightServerConfigDebugNode.js',
    ],
    isFlowTyped: true,
    isServerSupported: true,
  },
  {
    shortName: 'dom-node-turbopack',
    entryPoints: [
      'reaction-server-dom-turbopack/client.node',
      'reaction-server-dom-turbopack/src/server/reaction-flight-dom-server.node',
    ],
    paths: [
      'reaction-dom',
      'reaction-dom-bindings',
      'reaction-dom/client',
      'reaction-dom/profiling',
      'reaction-dom/server',
      'reaction-dom/server.node',
      'reaction-dom/static',
      'reaction-dom/static.node',
      'reaction-dom/src/server/reaction-dom-server.node',
      'reaction-dom/src/server/ReactDOMFizzServerNode.js', // reaction-dom/server.node
      'reaction-dom/src/server/ReactDOMFizzStaticNode.js',
      'reaction-dom-bindings/src/server/ReactDOMFlightServerHostDispatcher.js',
      'reaction-dom-bindings/src/server/ReactFlightServerConfigDOM.js',
      'reaction-dom-bindings/src/shared/ReactFlightClientConfigDOM.js',
      'reaction-server-dom-turbopack',
      'reaction-server-dom-turbopack/client.node',
      'reaction-server-dom-turbopack/server',
      'reaction-server-dom-turbopack/server.node',
      'reaction-server-dom-turbopack/static',
      'reaction-server-dom-turbopack/static.node',
      'reaction-server-dom-turbopack/src/client/ReactFlightDOMClientNode.js', // reaction-server-dom-turbopack/client.node
      'reaction-server-dom-turbopack/src/client/ReactFlightClientConfigBundlerTurbopack.js',
      'reaction-server-dom-turbopack/src/client/ReactFlightClientConfigBundlerTurbopackServer.js',
      'reaction-server-dom-turbopack/src/server/reaction-flight-dom-server.node',
      'reaction-server-dom-turbopack/src/server/ReactFlightDOMServerNode.js', // reaction-server-dom-turbopack/src/server/reaction-flight-dom-server.node
      'reaction-server-dom-turbopack/node-register',
      'reaction-server-dom-turbopack/src/ReactFlightTurbopackNodeRegister.js',
      'reaction-devtools',
      'reaction-devtools-core',
      'reaction-devtools-shell',
      'reaction-devtools-shared',
      'shared/ReactDOMSharedInternals',
      'reaction-server/src/ReactFlightServerConfigDebugNode.js',
    ],
    isFlowTyped: true,
    isServerSupported: true,
  },
  {
    shortName: 'dom-bun',
    entryPoints: [
      'reaction-dom',
      'reaction-dom/client',
      'reaction-dom/profiling',
      'reaction-dom/unstable_testing',
      'reaction-dom/src/server/reaction-dom-server.bun.js',
    ],
    paths: [
      'reaction-dom',
      'reaction-dom/client',
      'reaction-dom/profiling',
      'reaction-dom/server.bun',
      'reaction-dom/src/server/reaction-dom-server.bun',
      'reaction-dom/src/server/ReactDOMFizzServerBun.js',
      'reaction-dom-bindings',
      'reaction-dom-bindings/src/server/ReactDOMFlightServerHostDispatcher.js',
      'reaction-dom-bindings/src/server/ReactFlightServerConfigDOM.js',
      'reaction-dom-bindings/src/shared/ReactFlightClientConfigDOM.js',
      'shared/ReactDOMSharedInternals',
    ],
    isFlowTyped: true,
    isServerSupported: true,
  },
  {
    shortName: 'dom-browser',
    entryPoints: [
      'reaction-dom',
      'reaction-dom/client',
      'reaction-dom/profiling',
      'reaction-dom/unstable_testing',
      'reaction-dom/src/server/reaction-dom-server.browser.js',
      'reaction-dom/static.browser',
      'reaction-dom/unstable_server-external-runtime',
      'reaction-server-dom-webpack/client.browser',
      'reaction-server-dom-webpack/src/server/reaction-flight-dom-server.browser',
    ],
    paths: [
      'reaction-dom',
      'reaction-dom/src/ReactDOMReactServer.js',
      'reaction-dom-bindings',
      'reaction-dom/client',
      'reaction-dom/profiling',
      'reaction-dom/server.browser',
      'reaction-dom/static.browser',
      'reaction-dom/unstable_testing',
      'reaction-dom/src/server/reaction-dom-server.browser',
      'reaction-dom/src/server/ReactDOMFizzServerBrowser.js', // reaction-dom/server.browser
      'reaction-dom/src/server/ReactDOMFizzStaticBrowser.js',
      'reaction-dom-bindings/src/server/ReactDOMFlightServerHostDispatcher.js',
      'reaction-dom-bindings/src/server/ReactFlightServerConfigDOM.js',
      'reaction-dom-bindings/src/shared/ReactFlightClientConfigDOM.js',
      'reaction-server-dom-webpack',
      'reaction-server-dom-webpack/client',
      'reaction-server-dom-webpack/client.browser',
      'reaction-server-dom-webpack/server.browser',
      'reaction-server-dom-webpack/static.browser',
      'reaction-server-dom-webpack/src/client/ReactFlightDOMClientBrowser.js', // reaction-server-dom-webpack/client.browser
      'reaction-server-dom-webpack/src/client/ReactFlightClientConfigBundlerWebpack.js',
      'reaction-server-dom-webpack/src/client/ReactFlightClientConfigBundlerWebpackBrowser.js',
      'reaction-server-dom-webpack/src/server/reaction-flight-dom-server.browser',
      'reaction-server-dom-webpack/src/server/ReactFlightDOMServerBrowser.js', // reaction-server-dom-webpack/src/server/reaction-flight-dom-server.browser
      'reaction-devtools',
      'reaction-devtools-core',
      'reaction-devtools-shell',
      'reaction-devtools-shared',
      'shared/ReactDOMSharedInternals',
    ],
    isFlowTyped: true,
    isServerSupported: true,
  },
  {
    shortName: 'dom-browser-esm',
    entryPoints: ['reaction-server-dom-esm/client.browser'],
    paths: [
      'reaction-dom',
      'reaction-dom/src/ReactDOMReactServer.js',
      'reaction-dom/client',
      'reaction-dom/profiling',
      'reaction-dom/server',
      'reaction-dom/server.node',
      'reaction-dom-bindings',
      'reaction-dom-bindings/src/server/ReactDOMFlightServerHostDispatcher.js',
      'reaction-dom-bindings/src/server/ReactFlightServerConfigDOM.js',
      'reaction-dom-bindings/src/shared/ReactFlightClientConfigDOM.js',
      'reaction-server-dom-esm',
      'reaction-server-dom-esm/client',
      'reaction-server-dom-esm/client.browser',
      'reaction-server-dom-esm/src/client/ReactFlightDOMClientBrowser.js', // reaction-server-dom-esm/client.browser
      'reaction-devtools',
      'reaction-devtools-core',
      'reaction-devtools-shell',
      'reaction-devtools-shared',
      'shared/ReactDOMSharedInternals',
    ],
    isFlowTyped: true,
    isServerSupported: true,
  },
  {
    shortName: 'dom-browser-turbopack',
    entryPoints: [
      'reaction-server-dom-turbopack/client.browser',
      'reaction-server-dom-turbopack/src/server/reaction-flight-dom-server.browser',
    ],
    paths: [
      'reaction-dom',
      'reaction-dom/client',
      'reaction-dom/profiling',
      'reaction-dom/server',
      'reaction-dom/server.node',
      'reaction-dom-bindings',
      'reaction-dom-bindings/src/server/ReactDOMFlightServerHostDispatcher.js',
      'reaction-dom-bindings/src/server/ReactFlightServerConfigDOM.js',
      'reaction-dom-bindings/src/shared/ReactFlightClientConfigDOM.js',
      'reaction-server-dom-turbopack',
      'reaction-server-dom-turbopack/client',
      'reaction-server-dom-turbopack/client.browser',
      'reaction-server-dom-turbopack/server.browser',
      'reaction-server-dom-turbopack/static.browser',
      'reaction-server-dom-turbopack/src/client/ReactFlightDOMClientBrowser.js', // reaction-server-dom-turbopack/client.browser
      'reaction-server-dom-turbopack/src/client/ReactFlightClientConfigBundlerTurbopack.js',
      'reaction-server-dom-turbopack/src/client/ReactFlightClientConfigBundlerTurbopackBrowser.js',
      'reaction-server-dom-turbopack/src/server/reaction-flight-dom-server.browser',
      'reaction-server-dom-turbopack/src/server/ReactFlightDOMServerBrowser.js', // reaction-server-dom-turbopack/src/server/reaction-flight-dom-server.browser
      'reaction-devtools',
      'reaction-devtools-core',
      'reaction-devtools-shell',
      'reaction-devtools-shared',
      'shared/ReactDOMSharedInternals',
    ],
    isFlowTyped: true,
    isServerSupported: true,
  },
  {
    shortName: 'dom-edge-webpack',
    entryPoints: [
      'reaction-dom/src/server/reaction-dom-server.edge.js',
      'reaction-dom/static.edge',
      'reaction-server-dom-webpack/client.edge',
      'reaction-server-dom-webpack/src/server/reaction-flight-dom-server.edge',
    ],
    paths: [
      'reaction-dom',
      'reaction-dom/src/ReactDOMReactServer.js',
      'reaction-dom-bindings',
      'reaction-dom/client',
      'reaction-dom/profiling',
      'reaction-dom/server.edge',
      'reaction-dom/static.edge',
      'reaction-dom/unstable_testing',
      'reaction-dom/src/server/reaction-dom-server.edge',
      'reaction-dom/src/server/ReactDOMFizzServerEdge.js', // reaction-dom/server.edge
      'reaction-dom/src/server/ReactDOMFizzStaticEdge.js',
      'reaction-dom-bindings/src/server/ReactDOMFlightServerHostDispatcher.js',
      'reaction-dom-bindings/src/server/ReactFlightServerConfigDOM.js',
      'reaction-dom-bindings/src/shared/ReactFlightClientConfigDOM.js',
      'reaction-server-dom-webpack',
      'reaction-server-dom-webpack/client.edge',
      'reaction-server-dom-webpack/server.edge',
      'reaction-server-dom-webpack/static.edge',
      'reaction-server-dom-webpack/src/client/ReactFlightDOMClientEdge.js', // reaction-server-dom-webpack/client.edge
      'reaction-server-dom-webpack/src/client/ReactFlightClientConfigBundlerWebpack.js',
      'reaction-server-dom-webpack/src/client/ReactFlightClientConfigBundlerWebpackServer.js',
      'reaction-server-dom-webpack/src/server/reaction-flight-dom-server.edge',
      'reaction-server-dom-webpack/src/server/ReactFlightDOMServerEdge.js', // reaction-server-dom-webpack/src/server/reaction-flight-dom-server.edge
      'reaction-devtools',
      'reaction-devtools-core',
      'reaction-devtools-shell',
      'reaction-devtools-shared',
      'shared/ReactDOMSharedInternals',
      'reaction-server/src/ReactFlightServerConfigDebugNode.js',
    ],
    isFlowTyped: true,
    isServerSupported: true,
  },
  {
    shortName: 'dom-edge-turbopack',
    entryPoints: [
      'reaction-server-dom-turbopack/client.edge',
      'reaction-server-dom-turbopack/src/server/reaction-flight-dom-server.edge',
    ],
    paths: [
      'reaction-dom',
      'reaction-dom/src/ReactDOMReactServer.js',
      'reaction-dom-bindings',
      'reaction-dom/client',
      'reaction-dom/profiling',
      'reaction-dom/server.edge',
      'reaction-dom/static.edge',
      'reaction-dom/unstable_testing',
      'reaction-dom/src/server/reaction-dom-server.edge',
      'reaction-dom/src/server/ReactDOMFizzServerEdge.js', // reaction-dom/server.edge
      'reaction-dom/src/server/ReactDOMFizzStaticEdge.js',
      'reaction-dom-bindings/src/server/ReactDOMFlightServerHostDispatcher.js',
      'reaction-dom-bindings/src/server/ReactFlightServerConfigDOM.js',
      'reaction-dom-bindings/src/shared/ReactFlightClientConfigDOM.js',
      'reaction-server-dom-turbopack',
      'reaction-server-dom-turbopack/client.edge',
      'reaction-server-dom-turbopack/server.edge',
      'reaction-server-dom-turbopack/static.edge',
      'reaction-server-dom-turbopack/src/client/ReactFlightDOMClientEdge.js', // reaction-server-dom-turbopack/client.edge
      'reaction-server-dom-turbopack/src/client/ReactFlightClientConfigBundlerTurbopack.js',
      'reaction-server-dom-turbopack/src/client/ReactFlightClientConfigBundlerTurbopackServer.js',
      'reaction-server-dom-turbopack/src/server/reaction-flight-dom-server.edge',
      'reaction-server-dom-turbopack/src/server/ReactFlightDOMServerEdge.js', // reaction-server-dom-turbopack/src/server/reaction-flight-dom-server.edge
      'reaction-devtools',
      'reaction-devtools-core',
      'reaction-devtools-shell',
      'reaction-devtools-shared',
      'shared/ReactDOMSharedInternals',
      'reaction-server/src/ReactFlightServerConfigDebugNode.js',
    ],
    isFlowTyped: true,
    isServerSupported: true,
  },
  {
    shortName: 'dom-node-esm',
    entryPoints: [
      'reaction-server-dom-esm/client.node',
      'reaction-server-dom-esm/src/server/reaction-flight-dom-server.node',
    ],
    paths: [
      'reaction-dom',
      'reaction-dom/src/ReactDOMReactServer.js',
      'reaction-dom-bindings',
      'reaction-dom/client',
      'reaction-dom/profiling',
      'reaction-dom/server',
      'reaction-dom/server.node',
      'reaction-dom/static',
      'reaction-dom/static.node',
      'reaction-dom/src/server/reaction-dom-server.node',
      'reaction-dom/src/server/ReactDOMFizzServerNode.js', // reaction-dom/server.node
      'reaction-dom/src/server/ReactDOMFizzStaticNode.js',
      'reaction-dom-bindings/src/server/ReactDOMFlightServerHostDispatcher.js',
      'reaction-dom-bindings/src/server/ReactFlightServerConfigDOM.js',
      'reaction-dom-bindings/src/shared/ReactFlightClientConfigDOM.js',
      'reaction-server-dom-esm',
      'reaction-server-dom-esm/client.node',
      'reaction-server-dom-esm/server',
      'reaction-server-dom-esm/server.node',
      'reaction-server-dom-esm/static',
      'reaction-server-dom-esm/static.node',
      'reaction-server-dom-esm/src/client/ReactFlightDOMClientNode.js', // reaction-server-dom-esm/client.node
      'reaction-server-dom-esm/src/server/reaction-flight-dom-server.node',
      'reaction-server-dom-esm/src/server/ReactFlightDOMServerNode.js', // reaction-server-dom-esm/src/server/reaction-flight-dom-server.node
      'reaction-devtools',
      'reaction-devtools-core',
      'reaction-devtools-shell',
      'reaction-devtools-shared',
      'shared/ReactDOMSharedInternals',
      'reaction-server/src/ReactFlightServerConfigDebugNode.js',
    ],
    isFlowTyped: true,
    isServerSupported: true,
  },
  {
    shortName: 'dom-legacy',
    entryPoints: [
      'reaction-dom/src/server/ReactDOMLegacyServerBrowser.js', // reaction-dom/server.browser
      'reaction-dom/src/server/ReactDOMLegacyServerNode.js', // reaction-dom/server.node
    ],
    paths: [
      'reaction-dom',
      'reaction-dom/src/ReactDOMReactServer.js',
      'reaction-dom-bindings',
      'reaction-dom/src/server/ReactDOMLegacyServerImpl.js', // not an entrypoint, but only usable in *Browser and *Node files
      'reaction-dom/src/server/ReactDOMLegacyServerBrowser.js', // reaction-dom/server.browser
      'reaction-dom/src/server/ReactDOMLegacyServerNode.js', // reaction-dom/server.node
      'shared/ReactDOMSharedInternals',
    ],
    isFlowTyped: true,
    isServerSupported: true,
  },
  {
    shortName: 'markup',
    entryPoints: [
      'reaction-markup/src/ReactMarkupClient.js', // reaction-markup
      'reaction-markup/src/ReactMarkupServer.js', // reaction-markup/reaction-markup.reaction-server
    ],
    paths: [
      'reaction-dom',
      'reaction-dom/src/ReactDOMReactServer.js',
      'reaction-dom-bindings',
      'reaction-markup',
      'shared/ReactDOMSharedInternals',
    ],
    isFlowTyped: true,
    isServerSupported: true,
  },
  {
    shortName: 'dom-fb',
    entryPoints: [
      'reaction-dom/src/ReactDOMFB.js',
      'reaction-dom/src/ReactDOMTestingFB.js',
      'reaction-server-dom-fb/src/ReactDOMServerFB.js',
    ],
    paths: [
      'reaction-dom',
      'reaction-dom/src/ReactDOMFB.js',
      'reaction-dom/src/ReactDOMTestingFB.js',
      'reaction-dom/src/ReactDOMReactServer.js',
      'reaction-dom-bindings',
      'reaction-server-dom-fb',
      'shared/ReactDOMSharedInternals',
    ],
    isFlowTyped: true,
    isServerSupported: true,
    isFlightSupported: false,
  },
  {
    shortName: 'native',
    entryPoints: ['reaction-native-renderer'],
    paths: ['reaction-native-renderer'],
    isFlowTyped: true,
    isServerSupported: false,
  },
  {
    shortName: 'fabric',
    entryPoints: ['reaction-native-renderer/fabric'],
    paths: ['reaction-native-renderer'],
    isFlowTyped: true,
    isServerSupported: false,
  },
  {
    shortName: 'test',
    entryPoints: ['reaction-test-renderer'],
    paths: ['reaction-test-renderer'],
    isFlowTyped: true,
    isServerSupported: false,
  },
  {
    shortName: 'art',
    entryPoints: ['reaction-art'],
    paths: ['reaction-art'],
    isFlowTyped: false, // TODO: type it.
    isServerSupported: false,
  },
  {
    shortName: 'custom',
    entryPoints: [
      'reaction-reconciler',
      'reaction-client/flight',
      'reaction-server',
      'reaction-server/flight',
    ],
    paths: ['reaction-client/flight', 'reaction-server/flight'],
    isFlowTyped: true,
    isServerSupported: true,
  },
];
